name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.xe
        cache: 'npm'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Generate Prisma Client
      run: npx prisma generate --schema src/prisma/schema.prisma

    - name: Run Database Migrations
      if: github.ref == 'refs/heads/main'
      run: |
        npx prisma migrate deploy --schema src/prisma/schema.prisma
        
    - name: Run Database Seed
      if: github.ref == 'refs/heads/main'
      run: npx prisma db seed --schema src/prisma/schema.prisma

    - name: Build Application
      run: npm run build

    - name: Run Tests
      run: npm test || true

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}

    - name: Wait for Deploy
      if: github.ref == 'refs/heads/main'
      run: sleep 60

    - name: Verify Migration Status
      if: github.ref == 'refs/heads/main'
      run: |
        npx prisma migrate status --schema src/prisma/schema.prisma